version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_rate_limit
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: postgres_contacts
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  postgres_data: